function H = toy_energy(y, p)
%TOY_ENERGY Conserved Hamiltonian for the toy dynamics.
t = y(:,1); pt = y(:,2); px = y(:,4); u = y(:,5); pu = y(:,6);
coupling = p.g * p.field;
H = 0.5*(pt.^2 + px.^2 + pu.^2) ...
    + 0.5*p.omega_t^2*t.^2 ...
    + 0.5*p.omega_u^2*u.^2 ...
    + 0.25*p.lambda*u.^4 ...
    + coupling*t.*u;
end
